import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientLayout from "./client-layout";
import GlowEffect from "../components/GlowEffect";  
// Removed the import statement for ClientLayout due to the error
import HologramBackground from "../components/HologramBackground";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased glow-container relative min-h-screen`}>
        <ClientLayout>
          <HologramBackground />
          <GlowEffect />
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
